name: Continuous Integration
#TEST
on:
  push:
    branches: [ ci-setup ]

jobs:
  ci:  
    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:12

        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_pgsql
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Create .env.test from secrets
        run: |
          echo "KERNEL_CLASS='App\Kernel'" > .env.test
          echo "APP_SECRET='${{ secrets.APP_SECRET }}'" >> .env.test
          echo "SYMFONY_DEPRECATIONS_HELPER=999999" >> .env.test
          echo "DATABASE_URL=pgsql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?charset=utf8" >> .env.test

      - name: Drop and recreate the test database
        run: |
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test

      - name: Run database schema
        run: php bin/console doctrine:schema:update --force --env=test   

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction --group=tests --purge-with-truncate

      - name: Compile assets (Sass)
        run: php bin/console sass:build

      - name: Run tests
        run: php bin/phpunit

   
